#############################################################################
# Makefile for building: game
# Generated by qmake (3.0) (Qt 5.0.1) on: ?? ?? 6 21:42:07 2016
# Project:  game.pro
# Template: app
# Command: D:\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\bin\qmake.exe -spec win32-g++ -o Makefile game.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: game.pro ../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/win32-g++/qmake.conf ../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/spec_pre.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/device_config.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/common/shell-win32.conf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/qconfig.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_clucene.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_core.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_designer.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_gui.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_help.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_network.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_qml.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_quick.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_script.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_sql.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_svg.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_v8.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_xml.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/qt_functions.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/qt_config.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/win32-g++/qmake.conf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/spec_post.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/exclusive_builds.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/default_pre.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/win32/default_pre.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/release.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/debug_and_release.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/default_post.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/shared.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/win32/rtti.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/warn_on.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/qt.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/resources.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/moc.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/win32/opengl.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/uic.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/win32/windows.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/testcase_targets.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/exceptions.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/yacc.prf \
		../../../../Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/mkspecs/features/lex.prf \
		game.pro \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Multimedia.prl \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Widgets.prl \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Network.prl \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Gui.prl \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Core.prl \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/libEGL.prl \
		D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/libGLESv2.prl
	$(QMAKE) -spec win32-g++ -o Makefile game.pro
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\spec_pre.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\device_config.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\common\shell-win32.conf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\qconfig.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_bootstrap.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_clucene.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_designercomponents.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_platformsupport.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_qmldevtools.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_quickparticles.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_v8.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_webkit.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\qt_functions.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\qt_config.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\win32-g++\qmake.conf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\spec_post.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\default_pre.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\win32\default_pre.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\release.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\debug_and_release.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\default_post.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\shared.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\win32\rtti.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\warn_on.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\qt.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\resources.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\moc.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\win32\opengl.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\uic.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\win32\windows.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\testcase_targets.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\exceptions.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\yacc.prf:
..\..\..\..\Programme\Qt\Qt5.0.1\5.0.1\mingw47_32\mkspecs\features\lex.prf:
game.pro:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Multimedia.prl:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Widgets.prl:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Network.prl:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Gui.prl:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/Qt5Core.prl:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/libEGL.prl:
D:/Programme/Qt/Qt5.0.1/5.0.1/mingw47_32/lib/libGLESv2.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile game.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
